loaded_robot:
  name: ur5_info.yaml
  link_radius: 0.05
  objective_mode: ECAA
  input_device: keyboard
obstacles:
  cuboids:
    - name: box1
      scale: [0.4172, 0.3578, 0.317]
      translation: [-1.548, -2.9476, -0.8055]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box2
      scale: [0.4021, 0.3012, 0.1136]
      translation: [-1.4862, -2.271, -0.9962]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box3
      scale: [0.3523, 0.3945, 0.2703]
      translation: [-1.1433, -2.7415, -0.9007]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box4
      scale: [0.3291, 0.4028, 0.1003]
      translation: [-1.7411, -2.5046, -1.0141]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box5
      scale: [0.3474, 0.3109, 0.281]
      translation: [-1.4321, -2.9318, -0.5696]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box6
      scale: [0.3317, 0.3345, 0.1855]
      translation: [-1.4404, -2.6002, -0.9224]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box7
      scale: [0.3825, 0.4037, 0.1958]
      translation: [-1.1852, -2.6957, -0.4965]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box8
      scale: [0.3149, 0.3049, 0.334]
      translation: [-1.3529, -3.1159, -0.8086]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box9
      scale: [0.3105, 0.3706, 0.3754]
      translation: [-1.1059, -2.984, -0.6926]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box10
      scale: [0.3127, 0.3342, 0.1468]
      translation: [-1.1804, -2.3713, -0.9886]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box11
      scale: [0.3679, 0.4472, 0.3506]
      translation: [-0.8521, -2.6721, -0.5161]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box12
      scale: [0.2617, 0.2312, 0.2738]
      translation: [-0.674, -2.4083, -0.8474]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box13
      scale: [0.2908, 0.2806, 0.1572]
      translation: [-0.9298, -2.2445, -0.9951]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box14
      scale: [0.2664, 0.4104, 0.2438]
      translation: [-0.5509, -2.56, -0.385]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box15
      scale: [0.3158, 0.3302, 0.2104]
      translation: [-0.4572, -2.5573, -0.9664]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box16
      scale: [0.28, 0.2949, 0.3125]
      translation: [-0.3742, -2.2813, -0.8895]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box17
      scale: [0.1163, 0.2904, 0.3681]
      translation: [-0.6159, -2.6275, -0.6888]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box18
      scale: [0.2615, 0.3184, 0.2967]
      translation: [-0.8852, -2.5218, -0.8897]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box19
      scale: [0.2963, 0.2848, 0.2144]
      translation: [-0.6917, -2.3726, -0.597]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box20
      scale: [0.2739, 0.2633, 0.1659]
      translation: [-0.6473, -2.2246, -0.9414]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box21
      scale: [0.0305, 0.4238, 0.6088]
      translation: [0.9138, -2.2265, 0.479]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box22
      scale: [0.2987, 0.1173, 0.3998]
      translation: [0.7341, -1.4644, -0.1236]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box23
      scale: [0.1635, 0.286, 0.3202]
      translation: [0.9775, -1.6205, -0.2835]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box24
      scale: [0.0254, 0.4073, 0.4551]
      translation: [0.9211, -1.8113, 0.4716]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box25
      scale: [0.1995, 0.3567, 0.5262]
      translation: [0.4078, -1.9049, 0.0252]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box26
      scale: [0.1409, 0.2591, 0.3424]
      translation: [0.9882, -1.4754, -0.0448]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box27
      scale: [0.1257, 0.2993, 0.361]
      translation: [0.9898, -1.735, 0.0561]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box28
      scale: [0.1407, 0.44, 0.3754]
      translation: [0.9813, -2.1129, 0.0528]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box29
      scale: [0.3213, 0.3502, 0.4132]
      translation: [0.7908, -1.4822, 0.2907]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box30
      scale: [0.2118, 0.3497, 0.5386]
      translation: [0.9467, -1.9006, -0.4047]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box31
      scale: [0.2859, 0.3948, 0.2663]
      translation: [-0.287, -2.8392, -0.6402]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box32
      scale: [0.2241, 0.2596, 0.2123]
      translation: [-0.3636, -3.1, -0.8702]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box33
      scale: [0.3716, 0.292, 0.2311]
      translation: [0.0489, -2.8584, -0.7013]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box34
      scale: [0.1911, 0.2688, 0.2384]
      translation: [-0.5497, -2.883, -0.915]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box35
      scale: [0.3177, 0.2215, 0.1934]
      translation: [0.1251, -3.0112, -0.8581]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box36
      scale: [0.3896, 0.3401, 0.0833]
      translation: [-0.5334, -2.8822, -0.2542]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box37
      scale: [0.1876, 0.2104, 0.2178]
      translation: [-0.5702, -3.1196, -0.875]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box38
      scale: [0.2577, 0.2931, 0.2361]
      translation: [-0.1642, -3.0403, -0.8453]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box39
      scale: [0.2678, 0.354, 0.1909]
      translation: [-0.4081, -2.7801, -0.9276]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box40
      scale: [0.3696, 0.2673, 0.268]
      translation: [-0.6206, -2.8983, -0.6515]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box41
      scale: [0.3654, 0.3407, 0.2893]
      translation: [0.0523, -2.2256, -0.41]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box42
      scale: [0.3114, 0.581, 0.3679]
      translation: [0.2029, -2.6077, 0.1296]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box43
      scale: [0.3136, 0.4092, 0.249]
      translation: [-0.3379, -2.6088, -0.3419]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box44
      scale: [0.3513, 0.4539, 0.1745]
      translation: [-0.0579, -1.9628, -0.5068]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box45
      scale: [0.2992, 0.4328, 0.2151]
      translation: [0.2247, -2.5478, -0.289]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box46
      scale: [0.3076, 0.4784, 0.3323]
      translation: [-0.0888, -2.5639, -0.3557]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box47
      scale: [0.2047, 0.4022, 0.6582]
      translation: [0.281, -2.0843, -0.0381]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box48
      scale: [0.5009, 0.4851, 0.2893]
      translation: [0.163, -3.0142, -0.1552]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box49
      scale: [0.3294, 0.2176, 0.3437]
      translation: [-0.0973, -2.825, 0.0993]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box50
      scale: [0.394, 0.4438, 0.3392]
      translation: [0.0371, -2.6137, -0.5762]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box51
      scale: [0.3037, 0.3174, 0.2614]
      translation: [0.5728, -1.2705, -0.1959]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box52
      scale: [0.1168, 0.3602, 0.3819]
      translation: [1.0023, -1.1453, 0.1767]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box53
      scale: [0.2081, 0.266, 0.264]
      translation: [0.958, -1.2469, -0.0763]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box54
      scale: [0.2798, 0.27, 0.1396]
      translation: [0.755, -1.0396, -0.1993]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box55
      scale: [0.1721, 0.3984, 0.3408]
      translation: [0.979, -0.8245, 0.0822]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box56
      scale: [0.195, 0.2401, 0.2343]
      translation: [0.8172, -1.2945, -0.1592]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box57
      scale: [0.2299, 0.2705, 0.2105]
      translation: [0.9564, -0.8701, -0.1806]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box58
      scale: [0.2154, 0.3592, 0.2278]
      translation: [0.5403, -1.0245, -0.1539]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box59
      scale: [0.3836, 0.3576, 0.1578]
      translation: [0.6435, -0.7958, -0.1884]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box60
      scale: [0.1926, 0.223, 0.2353]
      translation: [0.9712, -1.1263, -0.1716]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box61
      scale: [0.3104, 0.2566, 0.0533]
      translation: [-0.9992, -1.0965, -1.0363]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box62
      scale: [0.2319, 0.2647, 0.0835]
      translation: [-1.001, -2.0755, -1.0128]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box63
      scale: [0.283, 0.253, 0.1191]
      translation: [-1.2376, -1.6423, -1.0176]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box64
      scale: [0.2963, 0.2889, 0.0834]
      translation: [-1.3559, -1.8103, -1.0342]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box65
      scale: [0.2588, 0.26, 0.0934]
      translation: [-0.9736, -1.3552, -1.0245]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box66
      scale: [0.2858, 0.2687, 0.0587]
      translation: [-1.4763, -2.0183, -1.0345]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box67
      scale: [0.2796, 0.3074, 0.0815]
      translation: [-1.1854, -1.3797, -1.0274]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box68
      scale: [0.2392, 0.281, 0.0797]
      translation: [-0.9753, -1.6355, -1.0226]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box69
      scale: [0.2183, 0.2647, 0.0879]
      translation: [-1.2335, -2.0663, -1.0207]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box70
      scale: [0.3245, 0.2268, 0.0816]
      translation: [-1.0398, -1.8506, -1.0099]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box71
      scale: [0.2464, 0.3169, 0.3805]
      translation: [0.6556, -2.5948, -0.6191]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box72
      scale: [0.3291, 0.2843, 0.2601]
      translation: [0.8728, -2.8346, -0.6638]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box73
      scale: [0.2213, 0.3062, 0.2974]
      translation: [0.9438, -3.064, -0.8222]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box74
      scale: [0.1649, 0.3867, 0.2195]
      translation: [0.776, -2.1585, -0.7735]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box75
      scale: [0.293, 0.6544, 0.3442]
      translation: [0.773, -2.8973, 0.0599]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box76
      scale: [0.1935, 0.3548, 0.2964]
      translation: [0.9239, -2.5501, -0.5872]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box77
      scale: [0.2508, 0.3378, 0.3219]
      translation: [0.7162, -2.436, -0.8982]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box78
      scale: [0.2031, 0.3739, 0.1961]
      translation: [0.8725, -2.8232, -0.9059]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box79
      scale: [0.3446, 0.4068, 0.4979]
      translation: [0.8327, -2.3099, -0.3284]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box80
      scale: [0.3436, 0.4655, 0.4193]
      translation: [0.8771, -2.6611, -0.1709]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box81
      scale: [0.295, 0.2565, 0.0679]
      translation: [-0.167, -1.0394, -0.2042]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box82
      scale: [0.2364, 0.2682, 0.2056]
      translation: [0.3232, -0.754, -0.1457]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box83
      scale: [0.2999, 0.232, 0.1103]
      translation: [-0.1051, -1.2776, -0.2318]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box84
      scale: [0.3135, 0.2894, 0.1664]
      translation: [-0.2651, -0.8307, -0.1998]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box85
      scale: [0.2185, 0.3546, 0.1181]
      translation: [-0.3329, -1.166, -0.2269]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box86
      scale: [0.3057, 0.2654, 0.1518]
      translation: [0.2624, -1.2572, -0.029]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box87
      scale: [0.3357, 0.271, 0.1666]
      translation: [0.2509, -0.9809, -0.0122]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box88
      scale: [0.2227, 0.2709, 0.3026]
      translation: [0.029, -1.5962, -0.3995]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box89
      scale: [0.2022, 0.3451, 0.1982]
      translation: [0.0561, -1.1949, -0.154]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box90
      scale: [0.2989, 0.3451, 0.1891]
      translation: [0.0455, -0.8335, -0.1494]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box91
      scale: [0.3231, 0.681, 0.4429]
      translation: [0.7452, -2.6878, 0.8455]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box92
      scale: [0.3892, 0.4186, 0.5671]
      translation: [-0.2298, -3.0631, 0.4912]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box93
      scale: [0.4003, 0.1709, 0.4016]
      translation: [-0.2539, -3.2504, 0.9857]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box94
      scale: [0.5769, 0.5529, 0.4526]
      translation: [0.1131, -2.9394, 0.228]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box95
      scale: [0.2922, 0.3696, 0.4319]
      translation: [0.7696, -3.0513, 0.2393]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box96
      scale: [0.2177, 0.3795, 0.3866]
      translation: [0.7979, -3.1535, 0.6389]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box97
      scale: [0.3902, 0.1276, 0.3915]
      translation: [0.1394, -3.2676, 1.0212]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box98
      scale: [0.3292, 0.4704, 0.4547]
      translation: [0.7644, -2.7165, 0.3871]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box99
      scale: [0.4133, 0.1838, 0.3749]
      translation: [0.1615, -3.1892, 0.6328]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box100
      scale: [0.2686, 0.3422, 0.3717]
      translation: [0.773, -3.1371, 1.0224]
      rotation: [0.0, 0.0, 0.0]
      animation: static
