loaded_robot:
  name: ur5_info.yaml
  link_radius: 0.05
  objective_mode: ECAA
  input_device: keyboard
obstacles:
  cuboids:
    - name: box1
      scale: [0.0913, 0.2143, 0.2507]
      translation: [1.0083, -1.716, -0.3189]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box2
      scale: [0.2152, 0.2421, 0.2377]
      translation: [-0.6596, -2.4526, -0.8368]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box3
      scale: [0.1994, 0.2814, 0.301]
      translation: [0.796, -3.1758, 0.694]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box4
      scale: [0.2198, 0.1894, 0.1288]
      translation: [0.7944, -1.0594, -0.2009]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box5
      scale: [0.2967, 0.2417, 0.0636]
      translation: [-1.0141, -1.3645, -1.0247]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box6
      scale: [0.1748, 0.1952, 0.2516]
      translation: [0.9437, -3.0438, -0.8311]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box7
      scale: [0.2753, 0.2148, 0.1117]
      translation: [-0.2795, -1.0638, -0.2261]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box8
      scale: [0.2376, 0.2553, 0.1073]
      translation: [-1.1725, -2.5139, -0.9692]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box9
      scale: [0.3526, 0.3124, 0.2275]
      translation: [0.0919, -2.8243, -0.1862]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box10
      scale: [0.2792, 0.095, 0.2294]
      translation: [-0.0536, -3.2789, 1.09]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box11
      scale: [0.1186, 0.2907, 0.2595]
      translation: [0.946, -2.5612, -0.5882]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box12
      scale: [0.3176, 0.2134, 0.086]
      translation: [-0.0435, -2.078, -0.501]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box13
      scale: [0.1689, 0.1702, 0.1954]
      translation: [0.8595, -1.2706, -0.1628]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box14
      scale: [0.3504, 0.0863, 0.3048]
      translation: [0.1701, -3.1897, 0.6184]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box15
      scale: [0.3315, 0.192, 0.1719]
      translation: [-0.4747, -3.1186, -0.8888]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box16
      scale: [0.0206, 0.3491, 0.3802]
      translation: [0.9222, -1.8482, 0.4645]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box17
      scale: [0.3519, 0.21, 0.2997]
      translation: [-1.3183, -3.149, -0.7921]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box18
      scale: [0.2767, 0.2287, 0.088]
      translation: [-1.2634, -1.74, -1.0154]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box19
      scale: [0.1585, 0.2452, 0.1407]
      translation: [0.1617, -1.1981, -0.0244]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box20
      scale: [0.1268, 0.2378, 0.1589]
      translation: [0.7629, -2.2019, -0.7561]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box21
      scale: [0.312, 0.3209, 0.1705]
      translation: [0.8854, -2.6842, -0.27]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box22
      scale: [0.1494, 0.2517, 0.2686]
      translation: [0.3423, -1.868, -0.1106]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box23
      scale: [0.3077, 0.2906, 0.2705]
      translation: [-0.7406, -2.6192, -0.5432]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box24
      scale: [0.2936, 0.1535, 0.2605]
      translation: [-0.1014, -2.8298, 0.1856]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box25
      scale: [0.135, 0.2285, 0.1995]
      translation: [1.0026, -0.9211, -0.1792]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box26
      scale: [0.2379, 0.2472, 0.3016]
      translation: [0.7756, -3.1604, 1.0362]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box27
      scale: [0.275, 0.2656, 0.1574]
      translation: [-0.4547, -2.5698, -0.966]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box28
      scale: [0.2916, 0.3236, 0.2292]
      translation: [-0.1783, -2.5655, -0.388]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box29
      scale: [0.2292, 0.237, 0.1316]
      translation: [-1.0177, -2.2402, -0.9953]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box30
      scale: [0.3125, 0.3332, 0.1619]
      translation: [0.0438, -2.7841, -0.6666]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box31
      scale: [0.2734, 0.2904, 0.2768]
      translation: [0.7707, -3.0658, 0.0537]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box32
      scale: [0.12, 0.3034, 0.2876]
      translation: [0.9914, -1.7241, 0.0513]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box33
      scale: [0.1809, 0.2307, 0.1282]
      translation: [0.6551, -1.2304, -0.2071]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box34
      scale: [0.2235, 0.1001, 0.3516]
      translation: [-0.3259, -3.2682, 0.9944]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box35
      scale: [0.2502, 0.2798, 0.2479]
      translation: [-0.5387, -2.879, -0.6698]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box36
      scale: [0.4032, 0.4814, 0.2572]
      translation: [-1.0576, -2.7918, -0.541]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box37
      scale: [0.2409, 0.1901, 0.1501]
      translation: [0.0156, -1.04, -0.1596]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box38
      scale: [0.3647, 0.3345, 0.0757]
      translation: [-0.5051, -2.8129, -0.2695]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box39
      scale: [0.2504, 0.2346, 0.1824]
      translation: [0.3902, -0.7433, -0.1558]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box40
      scale: [0.3109, 0.2855, 0.3644]
      translation: [0.7448, -2.8629, 0.8574]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box41
      scale: [0.2346, 0.2189, 0.0769]
      translation: [-1.4276, -2.3985, -0.9861]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box42
      scale: [0.2935, 0.2454, 0.2917]
      translation: [-1.5662, -2.9755, -0.8083]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box43
      scale: [0.2611, 0.2575, 0.0677]
      translation: [-1.2047, -1.4758, -1.0327]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box44
      scale: [0.2312, 0.0903, 0.3698]
      translation: [0.2096, -3.2528, 1.0078]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box45
      scale: [0.1026, 0.3667, 0.3292]
      translation: [0.3358, -3.0089, 0.294]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box46
      scale: [0.2733, 0.3394, 0.1908]
      translation: [0.8465, -2.3245, -0.4299]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box47
      scale: [0.3028, 0.2591, 0.1738]
      translation: [-0.4865, -2.859, -0.9353]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box48
      scale: [0.1096, 0.2901, 0.273]
      translation: [1.0076, -0.7907, 0.0614]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box49
      scale: [0.2999, 0.1699, 0.1028]
      translation: [-0.2747, -1.2708, -0.2335]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box50
      scale: [0.1189, 0.3014, 0.2289]
      translation: [0.2633, -2.1173, -0.2705]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box51
      scale: [0.1251, 0.2604, 0.2124]
      translation: [0.9939, -1.4854, -0.1603]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box52
      scale: [0.2886, 0.2392, 0.0692]
      translation: [-1.0503, -1.9658, -1.0138]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box53
      scale: [0.225, 0.2439, 0.21]
      translation: [-0.9068, -2.5001, -0.9221]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box54
      scale: [0.0871, 0.2153, 0.2192]
      translation: [0.0871, -1.6481, -0.3798]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box55
      scale: [0.2589, 0.3161, 0.2858]
      translation: [0.2639, -3.0463, -0.0794]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box56
      scale: [0.2204, 0.2302, 0.1318]
      translation: [0.8248, -0.8202, -0.2007]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box57
      scale: [0.2997, 0.2417, 0.068]
      translation: [-0.4137, -2.2624, -0.9913]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box58
      scale: [0.2895, 0.2361, 0.1161]
      translation: [-0.2509, -0.8168, -0.2224]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box59
      scale: [0.3051, 0.2598, 0.3576]
      translation: [0.7616, -2.7897, 0.4522]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box60
      scale: [0.1371, 0.4228, 0.291]
      translation: [0.9813, -2.1348, 0.0796]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box61
      scale: [0.1606, 0.2964, 0.156]
      translation: [0.8675, -2.8243, -0.9137]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box62
      scale: [0.1963, 0.2706, 0.2727]
      translation: [0.6645, -2.5806, -0.6288]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box63
      scale: [0.161, 0.0796, 0.301]
      translation: [0.7054, -1.484, 0.0654]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box64
      scale: [0.3438, 0.0807, 0.3092]
      translation: [-0.237, -3.2074, 0.5907]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box65
      scale: [0.192, 0.1437, 0.1989]
      translation: [0.7316, -1.4176, -0.2049]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box66
      scale: [0.2705, 0.2512, 0.0468]
      translation: [-1.5471, -2.1872, -1.024]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box67
      scale: [0.3042, 0.3547, 0.2712]
      translation: [0.7968, -1.4373, 0.3397]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box68
      scale: [0.263, 0.2318, 0.0364]
      translation: [-0.9949, -1.1007, -1.0358]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box69
      scale: [0.1372, 0.2097, 0.2083]
      translation: [0.9935, -1.1701, -0.1716]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box70
      scale: [0.2816, 0.2399, 0.1461]
      translation: [0.064, -0.8048, -0.1683]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box71
      scale: [0.2313, 0.2784, 0.0607]
      translation: [-0.9896, -1.6737, -1.0242]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box72
      scale: [0.2976, 0.3051, 0.1548]
      translation: [0.1964, -2.5374, -0.2979]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box73
      scale: [0.1789, 0.2728, 0.2825]
      translation: [0.8203, -3.0568, 0.3661]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box74
      scale: [0.1135, 0.2522, 0.3213]
      translation: [1.0038, -1.0788, 0.144]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box75
      scale: [0.1854, 0.2702, 0.1575]
      translation: [0.6207, -0.9, -0.1877]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box76
      scale: [0.1139, 0.2819, 0.2401]
      translation: [1.0006, -1.3662, 0.045]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box77
      scale: [0.2181, 0.3408, 0.3257]
      translation: [0.8089, -2.7068, 0.0684]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box78
      scale: [0.2202, 0.246, 0.0805]
      translation: [-1.2652, -2.2199, -1.0129]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box79
      scale: [0.0234, 0.4406, 0.4885]
      translation: [0.9122, -2.2636, 0.5798]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box80
      scale: [0.1608, 0.4904, 0.2908]
      translation: [0.3136, -2.188, 0.1623]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box81
      scale: [0.3068, 0.1248, 0.2556]
      translation: [-0.0797, -3.2336, 0.808]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box82
      scale: [0.2811, 0.292, 0.2222]
      translation: [-1.3972, -2.9204, -0.5652]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box83
      scale: [0.2686, 0.1771, 0.3285]
      translation: [0.2106, -2.7608, 0.1589]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box84
      scale: [0.2826, 0.2683, 0.2771]
      translation: [0.0531, -2.3098, -0.4123]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box85
      scale: [0.249, 0.2725, 0.3072]
      translation: [-0.2512, -2.9836, -0.773]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box86
      scale: [0.2666, 0.239, 0.1764]
      translation: [-0.7366, -2.2339, -0.9569]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box87
      scale: [0.2811, 0.2161, 0.2022]
      translation: [0.8832, -2.8364, -0.664]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box88
      scale: [0.3743, 0.1719, 0.1695]
      translation: [0.0561, -3.0621, -0.8511]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box89
      scale: [0.2899, 0.2141, 0.1255]
      translation: [0.2801, -0.9545, -0.0022]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box90
      scale: [0.2464, 0.2022, 0.1773]
      translation: [-0.6722, -2.3561, -0.6013]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box91
      scale: [0.2616, 0.2253, 0.1501]
      translation: [-1.4566, -2.6461, -0.9175]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box92
      scale: [0.2177, 0.2225, 0.089]
      translation: [-0.0764, -1.8253, -0.5366]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box93
      scale: [0.312, 0.3018, 0.2129]
      translation: [-1.1587, -2.828, -0.8818]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box94
      scale: [0.1613, 0.2442, 0.2331]
      translation: [0.6956, -2.4099, -0.8707]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box95
      scale: [0.2625, 0.2648, 0.0569]
      translation: [-1.3747, -1.9489, -1.0379]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box96
      scale: [0.2531, 0.2286, 0.1498]
      translation: [-0.4756, -2.4896, -0.3653]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box97
      scale: [0.0368, 0.2258, 0.2552]
      translation: [1.0309, -1.9189, -0.2191]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box98
      scale: [0.2375, 0.208, 0.1282]
      translation: [0.0142, -1.259, -0.1961]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box99
      scale: [0.1594, 0.3158, 0.1627]
      translation: [0.4841, -1.2232, -0.0669]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box100
      scale: [0.2501, 0.2726, 0.0771]
      translation: [-1.7275, -2.5305, -1.0243]
      rotation: [0.0, 0.0, 0.0]
      animation: static
