loaded_robot:
  name: ur5_info.yaml
  link_radius: 0.05
  objective_mode: ECAA
  input_device: keyboard
obstacles:
  cuboids:
    - name: box1
      scale: [0.1052, 0.2304, 0.2277]
      translation: [1.0085, -0.7895, 0.0578]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box2
      scale: [0.2218, 0.1873, 0.1224]
      translation: [-0.4745, -2.4901, -0.3566]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box3
      scale: [0.2439, 0.1794, 0.1004]
      translation: [0.8424, -2.4533, -0.3871]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box4
      scale: [0.2353, 0.2201, 0.0286]
      translation: [-0.9939, -1.1152, -1.0358]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box5
      scale: [0.2187, 0.1878, 0.0961]
      translation: [-1.0853, -2.2278, -1.0068]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box6
      scale: [0.1889, 0.0766, 0.3134]
      translation: [-0.3284, -3.2676, 1.0039]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box7
      scale: [0.1121, 0.2026, 0.1008]
      translation: [0.1745, -1.1945, -0.0132]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box8
      scale: [0.2966, 0.2322, 0.3217]
      translation: [0.744, -2.8672, 0.8467]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box9
      scale: [0.0389, 0.1802, 0.169]
      translation: [1.0352, -1.466, -0.1494]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box10
      scale: [0.2508, 0.2674, 0.1155]
      translation: [0.0492, -2.8068, -0.6661]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box11
      scale: [0.2953, 0.1866, 0.2645]
      translation: [-1.3181, -3.1454, -0.7996]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box12
      scale: [0.2505, 0.2105, 0.0967]
      translation: [-0.2598, -0.8198, -0.224]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box13
      scale: [0.2619, 0.1933, 0.0747]
      translation: [-0.0507, -2.0398, -0.5015]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box14
      scale: [0.1499, 0.2414, 0.1951]
      translation: [-0.5593, -2.8148, -0.9227]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box15
      scale: [0.1333, 0.2446, 0.1167]
      translation: [0.8667, -2.835, -0.9243]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box16
      scale: [0.2222, 0.2045, 0.1307]
      translation: [0.6943, -0.8473, -0.1994]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box17
      scale: [0.2409, 0.1181, 0.2855]
      translation: [0.2179, -2.779, 0.1697]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box18
      scale: [0.1204, 0.1636, 0.2066]
      translation: [0.6901, -2.389, -0.8693]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box19
      scale: [0.2374, 0.2178, 0.0536]
      translation: [-1.0135, -1.6946, -1.0217]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box20
      scale: [0.1139, 0.229, 0.2191]
      translation: [0.9939, -1.6499, 0.0545]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box21
      scale: [0.19, 0.2279, 0.0637]
      translation: [-1.7198, -2.5401, -1.0296]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box22
      scale: [0.2459, 0.1832, 0.1359]
      translation: [-0.2685, -2.9317, -0.6827]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box23
      scale: [0.2336, 0.2071, 0.3864]
      translation: [0.7844, -3.0781, 0.1496]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box24
      scale: [0.2206, 0.2194, 0.1869]
      translation: [-1.3954, -2.936, -0.559]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box25
      scale: [0.2521, 0.2298, 0.1852]
      translation: [-0.7185, -2.6035, -0.5487]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box26
      scale: [0.1507, 0.1889, 0.1167]
      translation: [0.65, -1.249, -0.2119]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box27
      scale: [0.1357, 0.2082, 0.1192]
      translation: [0.0621, -1.1779, -0.1749]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box28
      scale: [0.1702, 0.1943, 0.156]
      translation: [-0.5536, -3.1015, -0.8932]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box29
      scale: [0.3213, 0.2575, 0.1874]
      translation: [0.0854, -2.8178, -0.2024]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box30
      scale: [0.1019, 0.2139, 0.2331]
      translation: [0.3569, -1.859, -0.1019]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box31
      scale: [0.2708, 0.202, 0.0826]
      translation: [-1.4956, -2.2859, -1.0006]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box32
      scale: [0.0171, 0.3007, 0.3206]
      translation: [0.9236, -1.8444, 0.4275]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box33
      scale: [0.0697, 0.1594, 0.2105]
      translation: [1.0182, -1.6742, -0.2904]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box34
      scale: [0.2696, 0.192, 0.0529]
      translation: [-0.4274, -2.251, -0.9905]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box35
      scale: [0.3058, 0.0723, 0.2569]
      translation: [0.1698, -3.1865, 0.6176]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box36
      scale: [0.2626, 0.2185, 0.137]
      translation: [0.9064, -2.7137, -0.2777]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box37
      scale: [0.1216, 0.1529, 0.1339]
      translation: [0.8438, -1.2714, -0.191]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box38
      scale: [0.2161, 0.2253, 0.1797]
      translation: [0.4031, -0.7511, -0.1557]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box39
      scale: [0.1516, 0.1578, 0.1292]
      translation: [0.985, -1.096, -0.2098]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box40
      scale: [0.1937, 0.2149, 0.1865]
      translation: [-0.5618, -2.8833, -0.6519]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box41
      scale: [0.2463, 0.2094, 0.254]
      translation: [0.058, -2.2788, -0.4118]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box42
      scale: [0.2364, 0.2014, 0.0599]
      translation: [-1.0551, -1.9642, -1.0157]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box43
      scale: [0.2426, 0.1866, 0.2202]
      translation: [-1.5523, -2.9761, -0.8143]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box44
      scale: [0.1082, 0.2242, 0.1811]
      translation: [1.0017, -1.3321, 0.0655]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box45
      scale: [0.2477, 0.1793, 0.1645]
      translation: [0.8945, -2.8435, -0.6678]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box46
      scale: [0.2317, 0.2486, 0.0918]
      translation: [0.0553, -0.8414, -0.1812]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box47
      scale: [0.2117, 0.1869, 0.2976]
      translation: [0.7783, -3.1658, 1.0155]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box48
      scale: [0.2062, 0.23, 0.059]
      translation: [-1.2197, -1.5595, -1.0281]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box49
      scale: [0.1723, 0.2237, 0.3294]
      translation: [0.8041, -3.164, 0.6101]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box50
      scale: [0.1516, 0.1008, 0.2078]
      translation: [0.729, -1.4355, -0.1738]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box51
      scale: [0.1993, 0.072, 0.3164]
      translation: [0.2144, -3.2531, 1.0073]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box52
      scale: [0.1653, 0.2711, 0.1073]
      translation: [-0.3392, -1.1795, -0.2286]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box53
      scale: [0.2471, 0.2439, 0.1007]
      translation: [0.2007, -2.5284, -0.2898]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box54
      scale: [0.2425, 0.2402, 0.2508]
      translation: [-0.0148, -1.7318, -0.4319]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box55
      scale: [0.2277, 0.2465, 0.2344]
      translation: [0.2577, -3.0316, -0.0956]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box56
      scale: [0.2157, 0.1968, 0.1363]
      translation: [-1.4554, -2.5917, -0.9247]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box57
      scale: [0.209, 0.1697, 0.1573]
      translation: [-0.6615, -2.3573, -0.5953]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box58
      scale: [0.2505, 0.0982, 0.2297]
      translation: [-0.0992, -2.8119, 0.1883]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box59
      scale: [0.237, 0.1744, 0.1034]
      translation: [0.2544, -0.9621, -0.0004]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box60
      scale: [0.0212, 0.3208, 0.2657]
      translation: [0.9202, -2.2688, 0.0857]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box61
      scale: [0.1738, 0.1699, 0.1547]
      translation: [0.981, -0.8896, -0.1907]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box62
      scale: [0.2844, 0.2172, 0.3033]
      translation: [0.7662, -2.82, 0.4437]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box63
      scale: [0.1599, 0.2348, 0.1793]
      translation: [0.672, -2.5698, -0.6492]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box64
      scale: [0.1802, 0.1623, 0.1259]
      translation: [0.7649, -1.0462, -0.2013]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box65
      scale: [0.2222, 0.1445, 0.1514]
      translation: [-0.3118, -3.1267, -0.8826]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box66
      scale: [0.2382, 0.0806, 0.1984]
      translation: [-0.0527, -3.277, 1.0948]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box67
      scale: [0.2997, 0.0605, 0.2699]
      translation: [-0.244, -3.2068, 0.5883]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box68
      scale: [0.2345, 0.2819, 0.1425]
      translation: [-1.1514, -2.7777, -0.9267]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box69
      scale: [0.1004, 0.2388, 0.182]
      translation: [0.2643, -2.1148, -0.2646]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box70
      scale: [0.233, 0.2062, 0.0868]
      translation: [-0.7705, -2.2372, -0.9875]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box71
      scale: [0.2507, 0.2048, 0.0424]
      translation: [-1.3785, -2.0834, -1.0319]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box72
      scale: [0.2066, 0.1931, 0.1489]
      translation: [-0.9317, -2.4936, -0.9462]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box73
      scale: [0.0313, 0.2087, 0.2204]
      translation: [1.0325, -1.8889, -0.3055]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box74
      scale: [0.3383, 0.4123, 0.2013]
      translation: [-1.0647, -2.8002, -0.5387]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box75
      scale: [0.2295, 0.1973, 0.1044]
      translation: [-0.3117, -2.891, -0.927]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box76
      scale: [0.1206, 0.1415, 0.1609]
      translation: [0.9991, -1.2333, -0.143]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box77
      scale: [0.0173, 0.3973, 0.3801]
      translation: [0.9109, -2.2282, 0.5862]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box78
      scale: [0.1374, 0.0591, 0.3911]
      translation: [0.7062, -1.4884, 0.2299]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box79
      scale: [0.0904, 0.1628, 0.1199]
      translation: [0.7513, -2.2149, -0.7461]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box80
      scale: [0.2671, 0.2224, 0.0491]
      translation: [-1.028, -1.3866, -1.0241]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box81
      scale: [0.3124, 0.1284, 0.1314]
      translation: [0.0496, -3.0473, -0.8591]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box82
      scale: [0.256, 0.1992, 0.0602]
      translation: [-1.3355, -1.8279, -1.0336]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box83
      scale: [0.111, 0.2087, 0.2792]
      translation: [1.0047, -1.0494, 0.1339]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box84
      scale: [0.1911, 0.1908, 0.0501]
      translation: [-0.1596, -1.0403, -0.2063]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box85
      scale: [0.0158, 0.3068, 0.2092]
      translation: [0.9401, -1.4164, 0.3297]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box86
      scale: [0.0597, 0.2275, 0.1812]
      translation: [0.9372, -2.2476, -0.4548]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box87
      scale: [0.2028, 0.2548, 0.2793]
      translation: [0.8073, -2.7619, 0.0572]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box88
      scale: [0.0971, 0.4081, 0.0569]
      translation: [0.3319, -2.18, 0.2752]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box89
      scale: [0.2347, 0.2102, 0.0717]
      translation: [-0.4536, -2.5529, -0.997]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box90
      scale: [0.3098, 0.2671, 0.0527]
      translation: [-0.5088, -2.793, -0.2736]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box91
      scale: [0.053, 0.3157, 0.3032]
      translation: [0.3498, -3.0207, 0.2894]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box92
      scale: [0.1953, 0.1791, 0.2061]
      translation: [-0.6569, -2.4285, -0.838]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box93
      scale: [0.1507, 0.3015, 0.1232]
      translation: [0.4839, -1.2156, -0.0844]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box94
      scale: [0.1505, 0.1543, 0.2114]
      translation: [0.9474, -3.0358, -0.8313]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box95
      scale: [0.2493, 0.2631, 0.1318]
      translation: [-0.1801, -2.552, -0.3473]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box96
      scale: [0.1922, 0.1641, 0.0789]
      translation: [-0.1187, -1.2738, -0.239]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box97
      scale: [0.1902, 0.2265, 0.0804]
      translation: [-1.2295, -2.4293, -0.9793]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box98
      scale: [0.2521, 0.1041, 0.2104]
      translation: [-0.0792, -3.2343, 0.8106]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box99
      scale: [0.1168, 0.2267, 0.2098]
      translation: [0.9898, -1.9305, -0.0091]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box100
      scale: [0.0889, 0.2389, 0.2159]
      translation: [0.9513, -2.5759, -0.5964]
      rotation: [0.0, 0.0, 0.0]
      animation: static
