loaded_robot:
  name: ur5_info.yaml
  link_radius: 0.05
  objective_mode: ECAA
  input_device: keyboard
obstacles:
  cuboids:
    - name: box1
      scale: [0.25, 0.18, 0.17]
      translation: [0.72, -0.02, -1.46]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box2
      scale: [0.23, 0.11, 0.15]
      translation: [0.81, 0.1, -1.63]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box3
      scale: [0.21, 0.23, 0.14]
      translation: [0.78, 0.01, -1.51]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box4
      scale: [0.11, 0.08, 0.1]
      translation: [0.63, -0.4, -1.66]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box5
      scale: [0.07, 0.07, 0.08]
      translation: [0.7, -0.37, -1.66]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box6
      scale: [0.08, 0.06, 0.05]
      translation: [0.76, -0.34, -1.67]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box7
      scale: [0.04, 0.04, 0.04]
      translation: [0.82, 0.33, -1.65]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box8
      scale: [0.05, 0.06, 0.03]
      translation: [0.86, 0.32, -1.63]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box9
      scale: [0.05, 0.05, 0.03]
      translation: [0.82, 0.29, -1.66]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box10
      scale: [0.08, 0.08, 0.07]
      translation: [-0.17, 0.28, -1.34]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box11
      scale: [0.0, 0.1, 0.09]
      translation: [-0.13, 0.35, -1.37]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box12
      scale: [0.08, 0.08, 0.08]
      translation: [-0.17, 0.34, -1.3]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box13
      scale: [0.56, 0.58, 0.37]
      translation: [0.2, -0.25, -1.27]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box14
      scale: [0.28, 0.46, 0.51]
      translation: [-0.81, -0.44, -1.34]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box15
      scale: [0.69, 0.27, 0.2]
      translation: [-0.42, -0.1, -1.15]
      rotation: [0.0, 0.0, 0.0]
      animation: static
