loaded_robot:
  name: ur5_info.yaml
  link_radius: 0.05
  objective_mode: ECAA
  input_device: keyboard
obstacles:
  cuboids:
    - name: box1
      scale: [0.0461, 0.0478, 0.0604]
      translation: [-0.307, -0.8729, -0.2011]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box2
      scale: [0.0607, 0.0697, 0.014]
      translation: [-0.3654, -0.7319, -0.216]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box3
      scale: [0.057, 0.0562, 0.041]
      translation: [-0.2365, -0.8869, -0.1985]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box4
      scale: [0.05, 0.0608, 0.0408]
      translation: [-0.22, -0.9646, -0.2004]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box5
      scale: [0.06, 0.064, 0.0432]
      translation: [-0.385, -0.853, -0.2604]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box6
      scale: [0.056, 0.075, 0.0406]
      translation: [-0.387, -0.9515, -0.2627]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box7
      scale: [0.0695, 0.069, 0.012]
      translation: [-0.2712, -0.7305, -0.22]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box8
      scale: [0.06, 0.0553, 0.0571]
      translation: [-0.255, -0.8226, -0.2365]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box9
      scale: [0.0568, 0.0694, 0.0414]
      translation: [-0.2934, -0.9597, -0.1893]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box10
      scale: [0.0782, 0.0482, 0.064]
      translation: [-0.3459, -0.8089, -0.239]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box11
      scale: [0.0595, 0.0615, 0.036]
      translation: [0.7948, -0.9042, -0.249]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box12
      scale: [0.0599, 0.06, 0.028]
      translation: [0.895, -0.965, -0.251]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box13
      scale: [0.069, 0.05, 0.033]
      translation: [0.9595, -0.9, -0.2515]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box14
      scale: [0.0865, 0.0495, 0.0055]
      translation: [0.8288, -0.8998, -0.1333]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box15
      scale: [0.06, 0.0545, 0.031]
      translation: [0.865, -0.8978, -0.2495]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box16
      scale: [0.05, 0.05, 0.027]
      translation: [0.829, -0.97, -0.2505]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box17
      scale: [0.059, 0.079, 0.01]
      translation: [0.7745, -0.9555, -0.135]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box18
      scale: [0.0597, 0.05, 0.034]
      translation: [0.9648, -0.97, -0.253]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box19
      scale: [0.059, 0.05, 0.029]
      translation: [0.7645, -0.97, -0.2525]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box20
      scale: [0.06, 0.054, 0.004]
      translation: [0.8545, -0.968, -0.136]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box21
      scale: [0.09, 0.07, 0.003]
      translation: [0.3, -0.74, -0.2465]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box22
      scale: [0.0782, 0.076, 0.005]
      translation: [0.4141, -0.753, -0.2455]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box23
      scale: [0.0714, 0.007, 0.0868]
      translation: [0.4607, -0.8565, -0.1316]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box24
      scale: [0.053, 0.065, 0.059]
      translation: [0.3915, -0.6605, -0.2155]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box25
      scale: [0.068, 0.062, 0.051]
      translation: [0.309, -0.816, -0.2205]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box26
      scale: [0.037, 0.0446, 0.072]
      translation: [0.4165, -0.6461, -0.128]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box27
      scale: [0.0755, 0.071, 0.029]
      translation: [0.4799, -0.8195, -0.2295]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box28
      scale: [0.0724, 0.056, 0.0198]
      translation: [0.5482, -0.6652, -0.2321]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box29
      scale: [0.07, 0.0432, 0.018]
      translation: [0.47, -0.6173, -0.235]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box30
      scale: [0.0688, 0.028, 0.078]
      translation: [0.3806, -0.839, -0.204]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box31
      scale: [0.0045, 0.0595, 0.0685]
      translation: [0.9617, -0.8142, 0.0393]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box32
      scale: [0.0126, 0.0606, 0.07]
      translation: [0.9617, -0.7553, -0.05]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box33
      scale: [0.003, 0.0596, 0.055]
      translation: [0.9595, -0.7155, 0.1665]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box34
      scale: [0.003, 0.0607, 0.0697]
      translation: [0.9645, -0.7256, 0.0401]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box35
      scale: [0.01, 0.0608, 0.0678]
      translation: [0.961, -0.8446, -0.0489]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box36
      scale: [0.0033, 0.0693, 0.0593]
      translation: [0.9676, -0.6694, -0.0247]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box37
      scale: [0.003, 0.0628, 0.059]
      translation: [0.9625, -0.6554, 0.1336]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box38
      scale: [0.053, 0.03, 0.047]
      translation: [0.9115, -0.78, -0.0685]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box39
      scale: [0.003, 0.0562, 0.06]
      translation: [0.9655, -0.6471, 0.055]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box40
      scale: [0.003, 0.0547, 0.062]
      translation: [0.9605, -0.7705, 0.116]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box41
      scale: [0.07, 0.0684, 0.048]
      translation: [-0.07, -0.9598, -0.212]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box42
      scale: [0.0381, 0.0825, 0.0447]
      translation: [-0.1326, -0.7515, -0.1316]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box43
      scale: [0.066, 0.0707, 0.0117]
      translation: [-0.038, -0.7903, -0.1949]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box44
      scale: [0.0632, 0.0752, 0.0532]
      translation: [-0.1734, -0.8506, -0.2184]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box45
      scale: [0.0778, 0.068, 0.049]
      translation: [-0.0639, -0.88, -0.2115]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box46
      scale: [0.07, 0.086, 0.021]
      translation: [-0.18, -0.732, -0.2205]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box47
      scale: [0.0492, 0.0461, 0.0583]
      translation: [-0.1164, -0.818, -0.1729]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box48
      scale: [0.0522, 0.0732, 0.044]
      translation: [-0.1499, -0.9515, -0.21]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box49
      scale: [0.067, 0.0654, 0.0522]
      translation: [-0.0915, -0.7137, -0.2151]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box50
      scale: [0.07, 0.0783, 0.0106]
      translation: [-0.01, -0.6959, -0.193]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box51
      scale: [0.0467, 0.056, 0.026]
      translation: [0.7716, -0.823, -0.252]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box52
      scale: [0.0544, 0.059, 0.0082]
      translation: [0.8922, -0.7419, -0.2665]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box53
      scale: [0.0605, 0.0465, 0.023]
      translation: [0.8047, -0.6923, -0.2545]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box54
      scale: [0.04, 0.06, 0.03]
      translation: [0.905, -0.825, -0.249]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box55
      scale: [0.05, 0.05, 0.03]
      translation: [0.97, -0.84, -0.249]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box56
      scale: [0.06, 0.0552, 0.008]
      translation: [0.825, -0.7626, -0.261]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box57
      scale: [0.0469, 0.057, 0.017]
      translation: [0.7452, -0.7395, -0.2575]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box58
      scale: [0.0058, 0.0101, 0.0055]
      translation: [0.8745, -0.7853, -0.0964]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box59
      scale: [0.05, 0.0431, 0.0302]
      translation: [0.84, -0.8365, -0.2479]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box60
      scale: [0.0581, 0.05, 0.034]
      translation: [0.9641, -0.78, -0.246]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box61
      scale: [0.003, 0.0665, 0.05]
      translation: [0.9535, -0.8828, 0.23]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box62
      scale: [0.004, 0.0506, 0.0556]
      translation: [0.962, -0.9687, -0.0028]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box63
      scale: [0.004, 0.0588, 0.0746]
      translation: [0.955, -0.9654, 0.1651]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box64
      scale: [0.0037, 0.05, 0.05]
      translation: [0.9588, -0.83, 0.13]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box65
      scale: [0.0035, 0.0615, 0.0715]
      translation: [0.9512, -0.9633, 0.2602]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box66
      scale: [0.0027, 0.0641, 0.051]
      translation: [0.9596, -0.8827, 0.0795]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box67
      scale: [0.0036, 0.0638, 0.0612]
      translation: [0.9588, -0.9589, 0.0744]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box68
      scale: [0.004, 0.06, 0.0511]
      translation: [0.957, -0.805, 0.1996]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box69
      scale: [0.004, 0.0495, 0.064]
      translation: [0.961, -0.9002, 0.003]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box70
      scale: [0.0026, 0.059, 0.057]
      translation: [0.9557, -0.8945, 0.1575]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box71
      scale: [0.0904, 0.005, 0.062]
      translation: [0.3002, -0.8475, -0.126]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box72
      scale: [0.07, 0.0716, 0.0146]
      translation: [0.29, -0.9432, -0.0357]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box73
      scale: [0.069, 0.06, 0.011]
      translation: [0.1995, -0.965, -0.0435]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box74
      scale: [0.08, 0.0466, 0.043]
      translation: [0.455, -0.8793, -0.0635]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box75
      scale: [0.0666, 0.0696, 0.024]
      translation: [0.4777, -0.9502, -0.055]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box76
      scale: [0.077, 0.06, 0.045]
      translation: [0.2435, -0.874, -0.0525]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box77
      scale: [0.0488, 0.0178, 0.0638]
      translation: [0.31, -0.9839, 0.0175]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box78
      scale: [0.0791, 0.035, 0.07]
      translation: [0.3555, -0.8675, -0.078]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box79
      scale: [0.0467, 0.0177, 0.0627]
      translation: [0.2504, -0.9869, 0.0186]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box80
      scale: [0.07, 0.0691, 0.0141]
      translation: [0.38, -0.9596, -0.0379]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box81
      scale: [0.07, 0.06, 0.0359]
      translation: [0.71, -0.875, -0.244]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box82
      scale: [0.06, 0.0762, 0.025]
      translation: [0.545, -0.8441, -0.2215]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box83
      scale: [0.07, 0.05, 0.0532]
      translation: [0.602, -0.901, -0.2296]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box84
      scale: [0.062, 0.0596, 0.0173]
      translation: [0.627, -0.8368, -0.2377]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box85
      scale: [0.0798, 0.0924, 0.0298]
      translation: [0.6971, -0.9296, -0.1241]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box86
      scale: [0.0509, 0.0679, 0.03]
      translation: [0.6996, -0.799, -0.251]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box87
      scale: [0.0644, 0.0662, 0.038]
      translation: [0.6872, -0.9571, -0.243]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box88
      scale: [0.081, 0.086, 0.03]
      translation: [0.6025, -0.938, -0.122]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box89
      scale: [0.0781, 0.058, 0.0592]
      translation: [0.604, -0.965, -0.2375]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box90
      scale: [0.0646, 0.0716, 0.023]
      translation: [0.613, -0.7492, -0.2305]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box91
      scale: [0.071, 0.068, 0.051]
      translation: [0.2195, -0.809, -0.2205]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box92
      scale: [0.06, 0.0906, 0.046]
      translation: [0.115, -0.9397, -0.062]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box93
      scale: [0.0695, 0.078, 0.012]
      translation: [0.0298, -0.954, -0.199]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box94
      scale: [0.06, 0.0958, 0.012]
      translation: [0.065, -0.718, -0.205]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box95
      scale: [0.07, 0.077, 0.057]
      translation: [0.1135, -0.9555, -0.1835]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box96
      scale: [0.0524, 0.01, 0.102]
      translation: [0.2028, -0.846, -0.114]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box97
      scale: [0.046, 0.052, 0.08]
      translation: [0.112, -0.899, -0.115]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box98
      scale: [0.067, 0.059, 0.0365]
      translation: [0.1185, -0.7955, -0.2238]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box99
      scale: [0.0644, 0.059, 0.054]
      translation: [0.139, -0.8745, -0.212]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box100
      scale: [0.066, 0.07, 0.012]
      translation: [0.058, -0.86, -0.201]
      rotation: [0.0, 0.0, 0.0]
      animation: static
