loaded_robot:
  name: ur5_info.yaml
  link_radius: 0.05
  objective_mode: ECAA
  input_device: keyboard
obstacles:
  cuboids:
    - name: box1
      scale: [0.1686, 0.2855, 0.0969]
      translation: [0.5295, -1.0021, -0.0918]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box2
      scale: [0.1773, 0.1801, 0.1256]
      translation: [0.7667, -1.0447, -0.2017]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box3
      scale: [0.1411, 0.1551, 0.1643]
      translation: [0.9872, -1.2532, -0.0942]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box4
      scale: [0.1053, 0.2801, 0.2297]
      translation: [1.0085, -0.8347, 0.0597]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box5
      scale: [0.1482, 0.1697, 0.1276]
      translation: [0.8198, -1.2897, -0.1998]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box6
      scale: [0.27, 0.2118, 0.059]
      translation: [0.6499, -0.8196, -0.2347]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box7
      scale: [0.1097, 0.2575, 0.2677]
      translation: [1.0021, -1.144, 0.1697]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box8
      scale: [0.183, 0.1806, 0.1439]
      translation: [0.9764, -0.8949, -0.1967]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box9
      scale: [0.166, 0.199, 0.1271]
      translation: [0.6128, -1.2636, -0.2071]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box10
      scale: [0.1472, 0.1623, 0.1292]
      translation: [0.9871, -1.124, -0.2068]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box11
      scale: [0.3431, 0.3437, 0.2208]
      translation: [0.115, -2.9369, -0.1239]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box12
      scale: [0.2674, 0.2119, 0.2511]
      translation: [0.0718, -2.2898, -0.4057]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box13
      scale: [0.2914, 0.2878, 0.0836]
      translation: [-0.2191, -2.5619, -0.3234]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box14
      scale: [0.2703, 0.2603, 0.1022]
      translation: [0.1877, -2.5478, -0.2843]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box15
      scale: [0.2202, 0.1911, 0.0801]
      translation: [-0.0533, -1.8305, -0.5242]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box16
      scale: [0.1007, 0.2675, 0.2817]
      translation: [0.2873, -2.0498, -0.1844]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box17
      scale: [0.3463, 0.0871, 0.1813]
      translation: [-0.0021, -2.7732, 0.1443]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box18
      scale: [0.143, 0.3398, 0.0493]
      translation: [0.3084, -2.2237, 0.2778]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box19
      scale: [0.1649, 0.3277, 0.1267]
      translation: [0.1152, -2.7239, -0.6378]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box20
      scale: [0.2728, 0.1717, 0.0724]
      translation: [-0.0412, -2.0805, -0.4991]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box21
      scale: [0.2113, 0.1868, 0.2909]
      translation: [0.7784, -3.1664, 1.0197]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box22
      scale: [0.2165, 0.0987, 0.2218]
      translation: [0.237, -2.8079, 0.2239]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box23
      scale: [0.2311, 0.3336, 0.259]
      translation: [0.7902, -2.851, 0.0734]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box24
      scale: [0.173, 0.2161, 0.3192]
      translation: [0.8036, -3.1685, 0.6256]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box25
      scale: [0.0933, 0.2287, 0.3159]
      translation: [0.6423, -2.8691, 0.8509]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box26
      scale: [0.1301, 0.2775, 0.3002]
      translation: [0.3199, -3.067, 0.0052]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box27
      scale: [0.1355, 0.1928, 0.3589]
      translation: [0.8341, -3.0887, 0.1874]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box28
      scale: [0.0203, 0.3268, 0.5173]
      translation: [0.9102, -2.4008, 0.569]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box29
      scale: [0.2821, 0.1956, 0.3083]
      translation: [0.7649, -2.8326, 0.449]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box30
      scale: [0.096, 0.2462, 0.3102]
      translation: [0.334, -3.0549, 0.4305]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box31
      scale: [0.2381, 0.3672, 0.1383]
      translation: [-0.4972, -2.6305, -0.3283]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box32
      scale: [0.3187, 0.1651, 0.1533]
      translation: [-0.4693, -3.1199, -0.8896]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box33
      scale: [0.2814, 0.2018, 0.0536]
      translation: [-0.4359, -2.2544, -0.9889]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box34
      scale: [0.2927, 0.2088, 0.2174]
      translation: [-0.2777, -2.9211, -0.7232]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box35
      scale: [0.2553, 0.2171, 0.2207]
      translation: [-0.7075, -2.3841, -0.8952]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box36
      scale: [0.3197, 0.2993, 0.2422]
      translation: [-0.6866, -2.8292, -0.6131]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box37
      scale: [0.2438, 0.2265, 0.1647]
      translation: [-0.4667, -2.5683, -0.9479]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box38
      scale: [0.2895, 0.2016, 0.2458]
      translation: [-0.0087, -3.0142, -0.7911]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box39
      scale: [0.2246, 0.2785, 0.2281]
      translation: [-0.674, -2.4249, -0.5728]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box40
      scale: [0.2835, 0.2212, 0.1529]
      translation: [-0.49, -2.8689, -0.9373]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box41
      scale: [0.2705, 0.1686, 0.0676]
      translation: [-0.8893, -2.1177, -1.0131]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box42
      scale: [0.1867, 0.2009, 0.0548]
      translation: [-0.9698, -1.3557, -1.0255]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box43
      scale: [0.2052, 0.1735, 0.0683]
      translation: [-1.2175, -1.6509, -1.0169]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box44
      scale: [0.2039, 0.1703, 0.0312]
      translation: [-1.4314, -2.0196, -1.0371]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box45
      scale: [0.2371, 0.2026, 0.0268]
      translation: [-0.9954, -1.1059, -1.0349]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box46
      scale: [0.196, 0.1771, 0.0546]
      translation: [-1.1817, -2.0651, -1.0172]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box47
      scale: [0.1908, 0.2118, 0.0487]
      translation: [-1.18, -1.4094, -1.0317]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box48
      scale: [0.2202, 0.1867, 0.0542]
      translation: [-1.3362, -1.8234, -1.0387]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box49
      scale: [0.1859, 0.213, 0.0519]
      translation: [-0.9777, -1.6404, -1.0256]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box50
      scale: [0.2089, 0.1888, 0.0487]
      translation: [-1.0489, -1.8918, -1.0208]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box51
      scale: [0.1338, 0.2081, 0.1275]
      translation: [0.0626, -1.1706, -0.1691]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box52
      scale: [0.2451, 0.2181, 0.1]
      translation: [-0.2626, -0.8238, -0.226]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box53
      scale: [0.2289, 0.1793, 0.1033]
      translation: [0.243, -1.004, 0.0005]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box54
      scale: [0.1919, 0.1673, 0.0789]
      translation: [-0.119, -1.2718, -0.2389]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box55
      scale: [0.187, 0.1903, 0.05]
      translation: [-0.1527, -1.04, -0.2067]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box56
      scale: [0.2837, 0.1952, 0.0963]
      translation: [0.2669, -1.2467, -0.0138]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box57
      scale: [0.1664, 0.2714, 0.1075]
      translation: [-0.3384, -1.1793, -0.2285]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box58
      scale: [0.18, 0.211, 0.1715]
      translation: [0.3349, -0.7483, -0.1605]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box59
      scale: [0.2237, 0.2499, 0.0806]
      translation: [0.043, -0.8397, -0.1847]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box60
      scale: [0.1445, 0.1389, 0.2301]
      translation: [0.0526, -1.6346, -0.39]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box61
      scale: [0.1602, 0.2382, 0.1759]
      translation: [0.6715, -2.5717, -0.6469]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box62
      scale: [0.1742, 0.229, 0.2271]
      translation: [0.9318, -2.9807, -0.8586]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box63
      scale: [0.2433, 0.1812, 0.0988]
      translation: [0.842, -2.455, -0.385]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box64
      scale: [0.1261, 0.1754, 0.2064]
      translation: [0.6935, -2.3989, -0.8693]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box65
      scale: [0.2632, 0.214, 0.2607]
      translation: [0.9034, -2.7109, -0.2145]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box66
      scale: [0.085, 0.1601, 0.1248]
      translation: [0.7478, -2.2223, -0.7506]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box67
      scale: [0.2439, 0.2025, 0.2206]
      translation: [0.896, -2.8353, -0.7088]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box68
      scale: [0.0916, 0.2449, 0.2141]
      translation: [0.9517, -2.5872, -0.5959]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box69
      scale: [0.0629, 0.156, 0.0986]
      translation: [0.247, -2.9948, -0.8795]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box70
      scale: [0.0636, 0.2288, 0.1844]
      translation: [0.9377, -2.2605, -0.4569]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box71
      scale: [0.253, 0.2983, 0.148]
      translation: [-1.1271, -2.7327, -0.937]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box72
      scale: [0.2281, 0.2015, 0.1346]
      translation: [-1.437, -2.5718, -0.9266]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box73
      scale: [0.2463, 0.2049, 0.2147]
      translation: [-1.5501, -2.973, -0.8235]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box74
      scale: [0.2702, 0.2134, 0.0772]
      translation: [-1.4885, -2.2644, -1.0058]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box75
      scale: [0.2011, 0.236, 0.0659]
      translation: [-1.7139, -2.5362, -1.0284]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box76
      scale: [0.2692, 0.4349, 0.2088]
      translation: [-1.1293, -2.7948, -0.5386]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box77
      scale: [0.1797, 0.2743, 0.1141]
      translation: [-0.9663, -2.3943, -0.9842]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box78
      scale: [0.1909, 0.2512, 0.0899]
      translation: [-1.2095, -2.349, -0.9926]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box79
      scale: [0.2193, 0.1941, 0.1948]
      translation: [-1.4084, -2.9501, -0.563]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box80
      scale: [0.303, 0.213, 0.2632]
      translation: [-1.3113, -3.1314, -0.7972]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box81
      scale: [0.1531, 0.0703, 0.1798]
      translation: [0.7316, -1.4508, -0.1886]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box82
      scale: [0.0341, 0.2586, 0.237]
      translation: [1.0319, -1.8433, -0.3147]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box83
      scale: [0.2806, 0.2976, 0.2401]
      translation: [0.8057, -1.497, 0.3447]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box84
      scale: [0.1277, 0.3064, 0.2812]
      translation: [0.9815, -2.0964, 0.0456]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box85
      scale: [0.07, 0.1791, 0.2043]
      translation: [0.3768, -1.8359, -0.0729]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box86
      scale: [0.1075, 0.2062, 0.2259]
      translation: [0.9997, -1.4681, 0.0196]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box87
      scale: [0.0205, 0.359, 0.3379]
      translation: [0.9203, -1.9348, 0.4789]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box88
      scale: [0.1171, 0.2321, 0.2374]
      translation: [0.9919, -1.7622, 0.0336]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box89
      scale: [0.1374, 0.0564, 0.2581]
      translation: [0.7063, -1.486, 0.0885]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box90
      scale: [0.088, 0.2259, 0.1595]
      translation: [1.0103, -1.563, -0.2244]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box91
      scale: [0.1802, 0.0678, 0.2079]
      translation: [-0.3158, -3.2504, 0.7985]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box92
      scale: [0.2308, 0.0803, 0.181]
      translation: [0.1912, -3.2491, 0.8337]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box93
      scale: [0.1918, 0.0504, 0.1961]
      translation: [0.18, -3.1763, 0.5861]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box94
      scale: [0.2109, 0.0834, 0.1886]
      translation: [-0.0388, -3.2775, 1.101]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box95
      scale: [0.1854, 0.0457, 0.2392]
      translation: [-0.0584, -3.18, 0.5856]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box96
      scale: [0.2399, 0.1527, 0.118]
      translation: [-0.1458, -2.8721, 0.2613]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box97
      scale: [0.2189, 0.0758, 0.1951]
      translation: [-0.3159, -3.2698, 1.0702]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box98
      scale: [0.1905, 0.0691, 0.2182]
      translation: [0.22, -3.2528, 1.0831]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box99
      scale: [0.2013, 0.0485, 0.1903]
      translation: [-0.2953, -3.2103, 0.5386]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box100
      scale: [0.1984, 0.0916, 0.1858]
      translation: [-0.0848, -3.2446, 0.8618]
      rotation: [0.0, 0.0, 0.0]
      animation: static
