loaded_robot:
  name: ur5_info.yaml
  link_radius: 0.05
  objective_mode: ECAA
  input_device: keyboard
obstacles:
  cuboids:
    - name: box1
      scale: [0.2733, 0.3606, 0.335]
      translation: [-0.2332, -2.9471, -0.7715]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box2
      scale: [0.2771, 0.2705, 0.2546]
      translation: [-0.695, -2.3806, -0.8853]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box3
      scale: [0.255, 0.3128, 0.3008]
      translation: [-0.6791, -2.4238, -0.5633]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box4
      scale: [0.3154, 0.2959, 0.0657]
      translation: [-0.4287, -2.2844, -0.9913]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box5
      scale: [0.2782, 0.3506, 0.2011]
      translation: [-0.4662, -2.667, -0.9369]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box6
      scale: [0.3429, 0.3948, 0.3079]
      translation: [-0.763, -2.7835, -0.42]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box7
      scale: [0.2408, 0.3215, 0.2772]
      translation: [-0.5364, -2.8532, -0.7026]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box8
      scale: [0.2799, 0.2954, 0.2874]
      translation: [0.0359, -2.9702, -0.7824]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box9
      scale: [0.3503, 0.379, 0.2028]
      translation: [-0.4183, -2.6047, -0.3544]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box10
      scale: [0.323, 0.3194, 0.177]
      translation: [-0.4766, -3.0495, -0.8954]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box11
      scale: [0.2826, 0.2482, 0.2229]
      translation: [-0.0349, -1.778, -0.4664]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box12
      scale: [0.2426, 0.3003, 0.1163]
      translation: [0.2243, -2.5276, -0.285]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box13
      scale: [0.2556, 0.2338, 0.2692]
      translation: [0.0642, -2.2632, -0.4072]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box14
      scale: [0.261, 0.3057, 0.0966]
      translation: [-0.0649, -2.6298, -0.2599]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box15
      scale: [0.3078, 0.2293, 0.0885]
      translation: [-0.0494, -2.0574, -0.5027]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box16
      scale: [0.116, 0.2604, 0.2226]
      translation: [0.2633, -2.1542, -0.2741]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box17
      scale: [0.2147, 0.3667, 0.2711]
      translation: [0.0902, -2.6118, -0.5565]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box18
      scale: [0.2021, 0.3017, 0.3061]
      translation: [0.2984, -2.0435, 0.1349]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box19
      scale: [0.2791, 0.2363, 0.1317]
      translation: [-0.1756, -2.4351, -0.363]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box20
      scale: [0.0932, 0.2298, 0.1726]
      translation: [0.3318, -1.8994, -0.2055]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box21
      scale: [0.3095, 0.2742, 0.2876]
      translation: [0.7425, -2.8995, 0.9183]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box22
      scale: [0.2707, 0.1248, 0.2628]
      translation: [-0.0284, -3.2323, 0.8134]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box23
      scale: [0.3726, 0.0755, 0.2238]
      translation: [-0.2092, -3.1981, 0.5452]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box24
      scale: [0.3212, 0.0827, 0.3]
      translation: [0.1855, -3.1889, 0.6247]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box25
      scale: [0.258, 0.1019, 0.2293]
      translation: [-0.3141, -3.2697, 1.0601]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box26
      scale: [0.2581, 0.0965, 0.2237]
      translation: [-0.0247, -3.2792, 1.0934]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box27
      scale: [0.2112, 0.0897, 0.3583]
      translation: [0.2199, -3.2521, 1.0139]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box28
      scale: [0.2056, 0.2531, 0.2562]
      translation: [0.7923, -3.2008, 0.7649]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box29
      scale: [0.2341, 0.2375, 0.2666]
      translation: [0.7768, -3.1668, 1.0598]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box30
      scale: [0.2195, 0.0823, 0.2571]
      translation: [-0.3049, -3.2487, 0.7824]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box31
      scale: [0.184, 0.089, 0.3139]
      translation: [0.7245, -1.4616, -0.132]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box32
      scale: [0.1206, 0.2695, 0.3015]
      translation: [0.991, -1.7625, 0.0556]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box33
      scale: [0.0261, 0.4836, 0.3996]
      translation: [0.919, -1.9657, 0.4966]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box34
      scale: [0.145, 0.2496, 0.1971]
      translation: [0.9844, -1.5197, -0.185]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box35
      scale: [0.094, 0.2022, 0.2524]
      translation: [1.0063, -1.7283, -0.3221]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box36
      scale: [0.3094, 0.3358, 0.3414]
      translation: [0.7927, -1.4937, 0.3058]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box37
      scale: [0.092, 0.1968, 0.3511]
      translation: [0.393, -1.8335, 0.0116]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box38
      scale: [0.1146, 0.2408, 0.2221]
      translation: [0.9976, -1.4654, 0.0573]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box39
      scale: [0.1361, 0.3624, 0.2969]
      translation: [0.9811, -2.1156, 0.0828]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box40
      scale: [0.0415, 0.2238, 0.2527]
      translation: [1.0283, -1.926, -0.2276]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box41
      scale: [0.1739, 0.2239, 0.1465]
      translation: [0.0521, -1.1765, -0.1719]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box42
      scale: [0.2405, 0.2298, 0.093]
      translation: [-0.0821, -0.7907, -0.1908]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box43
      scale: [0.2693, 0.2124, 0.1156]
      translation: [0.2604, -0.99, 0.0034]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box44
      scale: [0.1367, 0.2271, 0.1163]
      translation: [0.1808, -1.2245, -0.0176]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box45
      scale: [0.1894, 0.2402, 0.1808]
      translation: [0.1005, -0.8954, -0.1458]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box46
      scale: [0.207, 0.29, 0.1096]
      translation: [-0.3084, -0.8601, -0.227]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box47
      scale: [0.2202, 0.231, 0.0572]
      translation: [-0.1554, -1.07, -0.2075]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box48
      scale: [0.3098, 0.3686, 0.0932]
      translation: [-0.0398, -1.407, -0.2462]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box49
      scale: [0.2049, 0.2751, 0.1131]
      translation: [-0.3276, -1.1973, -0.2268]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box50
      scale: [0.1898, 0.2279, 0.1923]
      translation: [0.3398, -0.7417, -0.1511]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box51
      scale: [0.2996, 0.1558, 0.2611]
      translation: [-0.0982, -2.828, 0.1852]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box52
      scale: [0.2717, 0.2785, 0.3442]
      translation: [0.7715, -3.0597, 0.0919]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box53
      scale: [0.2593, 0.3111, 0.2925]
      translation: [0.2654, -3.0611, -0.0701]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box54
      scale: [0.1112, 0.3532, 0.3335]
      translation: [0.3316, -3.0146, 0.2992]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box55
      scale: [0.3726, 0.2897, 0.2498]
      translation: [0.1127, -2.8515, -0.1717]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box56
      scale: [0.0295, 0.402, 0.6059]
      translation: [0.9138, -2.4918, 0.6121]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box57
      scale: [0.226, 0.3208, 0.354]
      translation: [0.8036, -2.7199, 0.0905]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box58
      scale: [0.3001, 0.2143, 0.4282]
      translation: [0.7538, -2.8335, 0.5222]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box59
      scale: [0.1842, 0.2848, 0.3522]
      translation: [0.8145, -3.1145, 0.4805]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box60
      scale: [0.2621, 0.313, 0.3196]
      translation: [0.2159, -2.6917, 0.1659]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box61
      scale: [0.2469, 0.2107, 0.0925]
      translation: [-1.2309, -1.6412, -1.0161]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box62
      scale: [0.2673, 0.2121, 0.0592]
      translation: [-1.0308, -1.8687, -1.0176]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box63
      scale: [0.2073, 0.2278, 0.0695]
      translation: [-0.967, -1.3471, -1.0263]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box64
      scale: [0.2166, 0.2321, 0.063]
      translation: [-0.9774, -1.6199, -1.0239]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box65
      scale: [0.2679, 0.2063, 0.0437]
      translation: [-1.4265, -2.0198, -1.0356]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box66
      scale: [0.2227, 0.2521, 0.0625]
      translation: [-1.1772, -1.3893, -1.0283]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box67
      scale: [0.3203, 0.212, 0.0787]
      translation: [-0.8546, -2.1092, -1.0101]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box68
      scale: [0.2372, 0.2154, 0.0677]
      translation: [-1.147, -2.0599, -1.0152]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box69
      scale: [0.2634, 0.2233, 0.0361]
      translation: [-0.9946, -1.0955, -1.0353]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box70
      scale: [0.2671, 0.2294, 0.0693]
      translation: [-1.3406, -1.8213, -1.0347]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box71
      scale: [0.1127, 0.2116, 0.1613]
      translation: [0.7554, -2.2188, -0.7605]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box72
      scale: [0.1964, 0.2718, 0.2732]
      translation: [0.6645, -2.5813, -0.6274]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box73
      scale: [0.2733, 0.3363, 0.191]
      translation: [0.8465, -2.3268, -0.4294]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box74
      scale: [0.2793, 0.2154, 0.201]
      translation: [0.8841, -2.8374, -0.6653]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box75
      scale: [0.1193, 0.2928, 0.2596]
      translation: [0.9455, -2.5622, -0.5886]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box76
      scale: [0.175, 0.196, 0.2521]
      translation: [0.9439, -3.0452, -0.8303]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box77
      scale: [0.3091, 0.3203, 0.21]
      translation: [0.8869, -2.6837, -0.2497]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box78
      scale: [0.0809, 0.2838, 0.2585]
      translation: [0.2434, -2.9319, -0.8017]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box79
      scale: [0.1614, 0.2462, 0.233]
      translation: [0.6956, -2.4127, -0.8708]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box80
      scale: [0.1624, 0.2993, 0.1533]
      translation: [0.8685, -2.8267, -0.9148]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box81
      scale: [0.3607, 0.263, 0.2981]
      translation: [-1.3067, -3.1212, -0.7901]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box82
      scale: [0.2119, 0.3197, 0.1483]
      translation: [-0.9505, -2.4024, -0.9829]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box83
      scale: [0.3268, 0.2564, 0.0967]
      translation: [-1.4906, -2.2648, -1.0004]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box84
      scale: [0.2757, 0.2693, 0.1579]
      translation: [-1.4331, -2.5829, -0.9256]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box85
      scale: [0.2781, 0.259, 0.2293]
      translation: [-1.4141, -2.9366, -0.5687]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box86
      scale: [0.3093, 0.2843, 0.2802]
      translation: [-1.5567, -2.9652, -0.8148]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box87
      scale: [0.2318, 0.3017, 0.1141]
      translation: [-1.2003, -2.3505, -0.9933]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box88
      scale: [0.3159, 0.4983, 0.2747]
      translation: [-1.1332, -2.784, -0.5403]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box89
      scale: [0.2527, 0.3074, 0.0805]
      translation: [-1.7197, -2.5136, -1.0225]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box90
      scale: [0.3094, 0.3464, 0.2084]
      translation: [-1.121, -2.7359, -0.916]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box91
      scale: [0.3202, 0.2873, 0.1994]
      translation: [0.6249, -0.8194, -0.1657]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box92
      scale: [0.1685, 0.1988, 0.1642]
      translation: [0.9793, -1.1244, -0.1971]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box93
      scale: [0.1099, 0.3387, 0.2773]
      translation: [1.0075, -0.825, 0.0633]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box94
      scale: [0.1702, 0.2643, 0.1488]
      translation: [0.6499, -1.2773, -0.2214]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box95
      scale: [0.1555, 0.205, 0.1937]
      translation: [0.8262, -1.2961, -0.1712]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box96
      scale: [0.1554, 0.1999, 0.2115]
      translation: [0.9824, -1.2452, -0.0879]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box97
      scale: [0.2247, 0.2283, 0.1701]
      translation: [0.9576, -0.8814, -0.1901]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box98
      scale: [0.2222, 0.2193, 0.1319]
      translation: [0.7543, -1.0357, -0.2005]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box99
      scale: [0.1126, 0.2983, 0.3106]
      translation: [1.0026, -1.1359, 0.1701]
      rotation: [0.0, 0.0, 0.0]
      animation: static
    - name: box100
      scale: [0.1694, 0.3581, 0.1586]
      translation: [0.4934, -1.1936, -0.069]
      rotation: [0.0, 0.0, 0.0]
      animation: static
